import { defineConfig } from 'oxlint'

export default defineConfig({
	env: {
		browser: true,
		builtin: true,
		node: true,
	},
	categories: {
		correctness: 'warn',
	},
	options: { typeAware: true, typeCheck: true },
	plugins: [
		'eslint',
		'react',
		'react-perf',
		'jsx-a11y',
		'typescript',
		'import',
		'promise',
		'jest',
		'unicorn',
	],
	jsPlugins: [
		{ name: 'react-hooks-js', specifier: 'eslint-plugin-react-hooks' },
		{
			name: 'eslint-tanstack-router',
			specifier: '@tanstack/eslint-plugin-router',
		},
		{
			name: 'eslint-tanstack-query',
			specifier: '@tanstack/eslint-plugin-query',
		},
	],
	ignorePatterns: ['dist', '.output', 'node_modules', 'src/routeTree.gen.ts'],
	rules: {
		// Tanstack Router rules, ref: https://tanstack.com/router/latest/docs/eslint/eslint-plugin-router
		'eslint-tanstack-router/create-route-property-order': 'error',
		// Tanstack Query rules, ref: https://tanstack.com/query/latest/docs/eslint/eslint-plugin-query
		'eslint-tanstack-query/exhaustive-deps': 'error',
		'eslint-tanstack-query/no-rest-destructuring': 'error',
		'eslint-tanstack-query/stable-query-client': 'error',
		'eslint-tanstack-query/no-unstable-deps': 'error',
		'eslint-tanstack-query/infinite-query-property-order': 'error',
		'eslint-tanstack-query/no-void-query-fn': 'warn',
		'eslint-tanstack-query/mutation-property-order': 'error',
		'eslint-tanstack-query/prefer-query-options': 'warn',

		// Recommended rules (from LintRulePreset.Recommended)
		// ref: https://github.com/TheAlexLichter/oxlint-react-compiler-rules/issues/1
		'react-hooks-js/component-hook-factories': 'error',
		'react-hooks-js/config': 'error',
		'react-hooks-js/error-boundaries': 'error',
		'react-hooks-js/gating': 'error',
		'react-hooks-js/globals': 'error',
		'react-hooks-js/immutability': 'error',
		'react-hooks-js/incompatible-library': 'error',
		'react-hooks-js/preserve-manual-memoization': 'error',
		'react-hooks-js/purity': 'error',
		'react-hooks-js/refs': 'error',
		'react-hooks-js/set-state-in-effect': 'warn',
		'react-hooks-js/set-state-in-render': 'error',
		'react-hooks-js/static-components': 'error',
		'react-hooks-js/unsupported-syntax': 'error',
		'react-hooks-js/use-memo': 'error',

		// Recommended-latest rules (from LintRulePreset.RecommendedLatest)
		'react-hooks-js/void-use-memo': 'error',

		// Off rules (LintRulePreset.Off) - not enabled by default
		'react-hooks-js/capitalized-calls': 'off',
		'react-hooks-js/fbt': 'off',
		'react-hooks-js/hooks': 'off',
		'react-hooks-js/invariant': 'off',
		'react-hooks-js/memoized-effect-dependencies': 'off',
		'react-hooks-js/no-deriving-state-in-effects': 'off',
		'react-hooks-js/rule-suppression': 'off',
		'react-hooks-js/syntax': 'off',
		'react-hooks-js/todo': 'off',

		// You can add more rules from: https://oxc.rs/docs/guide/usage/linter/rules.html?sort=fix&dir=asc&has_fix=true
		'eslint/arrow-body-style': [
			'error',
			'as-needed',
			{ requireReturnForObjectLiteral: true },
		],
		'typescript/consistent-indexed-object-style': ['error', 'record'],
		'jest/consistent-test-it': ['error', { fn: 'it' }],
		'eslint/curly': ['error', 'multi-line'],
		'unicorn/escape-case': 'warn',
		'unicorn/explicit-length-check': 'warn',
		'react/jsx-fragments': ['error', 'syntax'],
		'react/jsx-props-no-spread-multi': 'error',
		'jsx-a11y/no-aria-hidden-on-focusable': 'error',
		'unicorn/no-array-reverse': 'warn',
		'unicorn/no-array-sort': 'warn',
		'eslint/no-console': ['warn', { allow: ['debug'] }],
		'eslint/no-else-return': 'error',
		'typescript/no-explicit-any': [
			'error',
			{ fixToUnknown: true, ignoreRestArgs: true },
		],
		'promise/no-new-statics': 'error',
		'jsx-a11y/no-redundant-roles': 'error',
		'import/no-relative-parent-imports': 'error',
		'eslint/no-var': 'warn',
		'unicorn/prefer-array-flat-map': 'error',
		'eslint/prefer-const': 'warn',
		'eslint/prefer-object-spread': 'error',
		'eslint/prefer-spread': 'warn',
		'unicorn/switch-case-braces': ['error', 'avoid'],
		'typescript/switch-exhaustiveness-check': 'error',
		'unicorn/throw-new-error': 'error',
		'jest/valid-title': 'error',
		'eslint/yoda': 'warn',

		// tseslint
		'for-direction': 'error',
		'no-async-promise-executor': 'error',
		'no-case-declarations': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-delete-var': 'error',
		'no-dupe-else-if': 'error',
		'no-duplicate-case': 'error',
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-empty-static-block': 'error',
		'no-ex-assign': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-global-assign': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-loss-of-precision': 'error',
		'no-misleading-character-class': 'error',
		'no-nonoctal-decimal-escape': 'error',
		'no-regex-spaces': 'error',
		'no-self-assign': 'error',
		'no-shadow': 'warn',
		'no-shadow-restricted-names': 'error',
		'no-sparse-arrays': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-optional-chaining': 'error',
		'no-unused-labels': 'error',
		'no-unused-private-class-members': 'error',
		'no-useless-backreference': 'error',
		'no-useless-catch': 'error',
		'no-useless-escape': 'error',
		'no-var': 'error',
		'no-with': 'error',
		'prefer-const': 'error',
		'require-yield': 'error',
		'use-isnan': 'error',
		'valid-typeof': 'error',
		'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
		'import/first': 'error',
		'import/no-commonjs': 'error',
		'import/no-duplicates': 'error',
		'typescript/array-type': [
			'error',
			{
				default: 'generic',
				readonly: 'generic',
			},
		],
		'typescript/ban-ts-comment': [
			'error',
			{
				'ts-expect-error': false,
				'ts-ignore': 'allow-with-description',
			},
		],
		'typescript/consistent-type-imports': [
			'error',
			{
				prefer: 'type-imports',
			},
		],
		'typescript/no-duplicate-enum-values': 'error',
		'typescript/no-extra-non-null-assertion': 'error',
		'typescript/no-for-in-array': 'error',
		'typescript/no-inferrable-types': [
			'error',
			{
				ignoreParameters: true,
			},
		],
		'typescript/no-misused-new': 'error',
		'typescript/no-namespace': 'error',
		'typescript/no-non-null-asserted-optional-chain': 'error',
		'typescript/no-unnecessary-condition': 'error',
		'typescript/no-unnecessary-type-assertion': 'error',
		'typescript/no-unsafe-function-type': 'error',
		'typescript/no-wrapper-object-types': 'error',
		'typescript/prefer-as-const': 'error',
		'typescript/prefer-for-of': 'warn',
		'typescript/require-await': 'warn',
		'typescript/triple-slash-reference': 'error',
		'constructor-super': 'off',
		'getter-return': 'off',
		'no-const-assign': 'off',
		'no-dupe-class-members': 'off',
		'no-dupe-keys': 'off',
		'no-func-assign': 'off',
		'no-import-assign': 'off',
		'no-new-native-nonconstructor': 'off',
		'no-obj-calls': 'off',
		'no-redeclare': 'off',
		'no-setter-return': 'off',
		'no-this-before-super': 'off',
		'no-undef': 'off',
		'no-unreachable': 'off',
		'no-unsafe-negation': 'off',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'no-array-constructor': 'error',
		'no-unused-expressions': 'error',
		'no-unused-vars': [
			'warn',
			{
				argsIgnorePattern: '^_',
			},
		],
		'typescript/no-empty-object-type': 'error',
		'typescript/no-require-imports': 'error',
		'typescript/no-this-alias': 'error',
		'typescript/no-unnecessary-type-constraint': 'error',
		'typescript/no-unsafe-declaration-merging': 'error',
		'typescript/prefer-namespace-keyword': 'error',
		'no-throw-literal': 'off',
		'prefer-promise-reject-errors': 'off',
		'require-await': 'off',
		'typescript/await-thenable': 'error',
		'typescript/no-array-delete': 'error',
		'typescript/no-base-to-string': 'error',
		'typescript/no-duplicate-type-constituents': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-implied-eval': 'error',
		'typescript/no-misused-promises': [
			'error',
			{
				checksVoidReturn: {
					attributes: false,
				},
			},
		],
		'typescript/no-redundant-type-constituents': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-enum-comparison': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/no-unsafe-unary-minus': 'error',
		'typescript/only-throw-error': 'off',
		'typescript/prefer-promise-reject-errors': 'error',
		'typescript/restrict-plus-operands': 'error',
		'typescript/restrict-template-expressions': 'error',
		'typescript/unbound-method': 'error',
		'no-empty-function': 'error',
		'typescript/adjacent-overload-signatures': 'error',
		'typescript/ban-tslint-comment': 'error',
		'typescript/class-literal-property-style': 'error',
		'typescript/consistent-generic-constructors': 'error',
		'typescript/consistent-type-assertions': 'error',
		'typescript/consistent-type-definitions': 'off',
		'typescript/dot-notation': 'error',
		'typescript/no-confusing-non-null-assertion': 'error',
		'typescript/non-nullable-type-assertion-style': 'error',
		'typescript/prefer-find': 'error',
		'typescript/prefer-function-type': 'error',
		'typescript/prefer-includes': 'error',
		'typescript/prefer-nullish-coalescing': 'error',
		'typescript/prefer-optional-chain': 'error',
		'typescript/prefer-regexp-exec': 'error',
		'typescript/prefer-string-starts-ends-with': 'error',
		'arrow-body-style': [
			'error',
			'as-needed',
			{ requireReturnForObjectLiteral: true },
		],

		'no-deprecated': 'warn',
		'typescript/no-misused-spread': 'off',

		// react
		'react/rules-of-hooks': 'error',
		'react/exhaustive-deps': 'warn',
		'react/no-children-prop': 'off',
	},
})
